import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import GlobalHeader from "./components/GlobalHeader";
import GlobalFooter from "./components/GlobalFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Advancelytics — Proactive AI That Turns Visitors into Customers",
    template: "%s | Advancelytics",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* <Script
          src="http://localhost:3000/api/widget"
          data-api-key="ak_b17dd57a2e0d78b5d3f1155e94167da890dda703409fe1e36e647c2e6cc8d345"
          data-theme="green"
          data-size="large"
          data-voice-enabled="true"
          data-voice-gender="female"
          data-auto-open-proactive="true"
          strategy="afterInteractive"
        /> */}
        <GlobalHeader />
        {children}
        <GlobalFooter />
      </body>
      <script
        src="https://agentlytics.advancelytics.com/api/widget"
        data-api-key="ak_b11073a2c223c1a1b8de748e2291cb68eb72d9a6a4c73f2204a8e4d4faf3b450"
        data-size="large"
        data-voice-enabled="false"
        data-voice-gender="female"
        data-auto-open-proactive="true"
      ></script>
    </html>
  );
}
