export const PRICING = {
  free: {
    id: "free",
    name: "Free",
    price: "$0",
    amount: 0,
    cadence: "",
    totalLeads: 20,
    creditsPerMonth: 500,
    websites: 1,
    razorpayPlanId: null,
  },
  growth: {
    id: "growth",
    name: "Growth",
    price: "$49",
    amount: 49,
    cadence: "month",
    totalLeads: 25_000,
    creditsPerMonth: 7_000,
    websites: 1,
    razorpayPlanId: process.env.NEXT_PUBLIC_RAZORPAY_PLAN_GROWTH,
  },
  scale: {
    id: "scale",
    name: "Scale",
    price: "$99",
    amount: 99,
    cadence: "month",
    totalLeads: 100_000,
    creditsPerMonth: 16_000,
    websites: 3,
    razorpayPlanId: process.env.NEXT_PUBLIC_RAZORPAY_PLAN_SCALE,
  },
} as const;
